spring.application.name=inventory-system

# ===============================
# DATABASE CONFIGURATION (H2 In-Memory)
# ===============================
spring.datasource.url=jdbc:h2:mem:inventory_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# CRITICAL: Faz o Spring esperar o Hibernate criar as tabelas antes de rodar o data.sql
spring.jpa.defer-datasource-initialization=true

# ===============================
# SQL INITIALIZATION
# ===============================
# Garante que scripts data.sql sejam lidos
spring.sql.init.mode=always

# ===============================
# H2 CONSOLE
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# CUSTOM LOGGING
# ===============================
logging.level.root=INFO
logging.level.com.leonardomuniz.inventorysystem=DEBUG
logging.file.name=logs/application.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# ===============================
# SWAGGER / OPENAPI CONFIG
# ===============================
# Acesso visual e documentação JSON
springdoc.swagger-ui.path=/products/swagger-ui.html
springdoc.api-docs.path=/products/api-docs

# Organização e Escaneamento
springdoc.swagger-ui.operationsSorter=alpha
springdoc.packages-to-scan=com.leonardomuniz.inventorysystem

# Habilita suporte para @Controller (Thymeleaf)
springdoc.model-and-view-allowed=true
